# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vanwykjd.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Josh Van Wyk
  avatar: BlocProfile.jpg
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>A Software Engineering Student training to become a Master</h1>
  header_text_feature_image: callout_banner.png
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "joshvanwyk@ymail.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: "joshvanwyk"
  flickr:
  github: "vanwykj"
  google_plus:
  instagram: 
  linkedin:  
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]